-- ============================================
-- Collabo Connect — D1 (SQLite) schema
-- ============================================
-- Ported from railway/schema.sql (Postgres). Differences:
--   * uuid columns        -> TEXT (ids generated by app default expression below)
--   * text[] / jsonb       -> TEXT holding JSON (db layer parses/serializes)
--   * boolean              -> INTEGER 0/1
--   * timestamptz / date   -> TEXT (ISO-8601 UTC / YYYY-MM-DD)
--   * get_profile_tags()   -> inline correlated subquery (see sql-helpers.ts)
--   * updated_at trigger   -> handled at the application layer
-- The id default mimics a v4 UUID so rows that omit id keep working.

-- ---- 1. profiles ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS profiles (
  -- id mirrors the Better Auth user.id. FK + ON DELETE CASCADE so deleting an
  -- auth user cleans up the profile and, transitively, that user's postings,
  -- participations, profile_tags, etc. (SQLite allows referencing the "user"
  -- table even though it is created later in this migration; the FK is only
  -- enforced at row time, by which point "user" exists.)
  id TEXT PRIMARY KEY REFERENCES "user"("id") ON DELETE CASCADE,
  name TEXT NOT NULL,
  avatar_url TEXT DEFAULT '',
  role TEXT DEFAULT '',
  areas TEXT DEFAULT '[]',
  job_type TEXT NOT NULL DEFAULT '',
  ai_intro TEXT DEFAULT '',
  nickname TEXT NOT NULL DEFAULT '',
  conversation_topics TEXT DEFAULT '[]',
  conversation_topics_updated_at TEXT,
  joined_date TEXT DEFAULT (date('now')),
  created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- ---- 2. postings ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS postings (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  title TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('food', 'study', 'event')),
  date TEXT,
  date_undecided INTEGER DEFAULT 0,
  area TEXT NOT NULL,
  is_online INTEGER DEFAULT 0,
  description TEXT DEFAULT '',
  creator_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS postings_creator_created_at_idx
  ON postings (creator_id, created_at DESC);

-- ---- 3. posting_participants ---------------------------------------------
CREATE TABLE IF NOT EXISTS posting_participants (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  posting_id TEXT NOT NULL REFERENCES postings(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  action TEXT NOT NULL CHECK (action IN ('join', 'interested', 'online')),
  created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  UNIQUE (posting_id, user_id)
);
CREATE INDEX IF NOT EXISTS posting_participants_user_id_idx
  ON posting_participants (user_id);

-- ---- 4. ai_questions ------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_questions (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  question TEXT NOT NULL,
  options TEXT DEFAULT '[]',
  -- One shared question per day; UNIQUE enables the cron's atomic
  -- INSERT ... ON CONFLICT (date) DO NOTHING (no duplicate on a manual+cron race).
  date TEXT DEFAULT (date('now')) UNIQUE,
  created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- ---- 5. ai_question_responses --------------------------------------------
CREATE TABLE IF NOT EXISTS ai_question_responses (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  question_id TEXT NOT NULL REFERENCES ai_questions(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  answer TEXT NOT NULL,
  created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  UNIQUE (question_id, user_id)
);
CREATE INDEX IF NOT EXISTS ai_question_responses_user_created_at_idx
  ON ai_question_responses (user_id, created_at DESC);

-- ---- 6. tags --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tags (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  name TEXT NOT NULL,
  aliases TEXT DEFAULT '[]',
  category TEXT NOT NULL DEFAULT 'other'
    CHECK (category IN ('skill', 'hobby', 'area', 'role', 'other')),
  usage_count INTEGER NOT NULL DEFAULT 0,
  created_by TEXT REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
-- Case-insensitive uniqueness; upsertTag uses ON CONFLICT (lower(name)).
CREATE UNIQUE INDEX IF NOT EXISTS tags_name_lower_unique_idx ON tags (lower(name));
CREATE INDEX IF NOT EXISTS tags_category_idx ON tags (category);
CREATE INDEX IF NOT EXISTS tags_usage_count_idx ON tags (usage_count DESC);

-- ---- 7. profile_tags ------------------------------------------------------
CREATE TABLE IF NOT EXISTS profile_tags (
  profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  tag_id TEXT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  source TEXT NOT NULL DEFAULT 'manual'
    CHECK (source IN ('manual', 'auto', 'interview', 'daily_question', 'posting')),
  created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  PRIMARY KEY (profile_id, tag_id)
);
CREATE INDEX IF NOT EXISTS profile_tags_tag_id_idx ON profile_tags (tag_id);

-- ---- 8. suggested_tags ----------------------------------------------------
CREATE TABLE IF NOT EXISTS suggested_tags (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  user_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  tag_id TEXT REFERENCES tags(id) ON DELETE CASCADE,
  proposed_name TEXT,
  proposed_category TEXT NOT NULL DEFAULT 'other'
    CHECK (proposed_category IN ('skill', 'hobby', 'area', 'role', 'other')),
  source TEXT NOT NULL CHECK (source IN ('interview', 'daily_question', 'posting')),
  confidence TEXT NOT NULL CHECK (confidence IN ('high', 'medium')),
  reason TEXT DEFAULT '',
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'accepted', 'rejected')),
  created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  resolved_at TEXT,
  CHECK (tag_id IS NOT NULL OR proposed_name IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS suggested_tags_user_status_idx
  ON suggested_tags (user_id, status);
CREATE INDEX IF NOT EXISTS suggested_tags_tag_id_idx
  ON suggested_tags (tag_id) WHERE tag_id IS NOT NULL;

-- ============================================
-- Better Auth core tables (SQLite). Mirrors the official generated schema.
-- ============================================
CREATE TABLE IF NOT EXISTS "user" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL UNIQUE,
  "emailVerified" INTEGER NOT NULL DEFAULT 0,
  "image" TEXT,
  "createdAt" DATE NOT NULL,
  "updatedAt" DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS "session" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "expiresAt" DATE NOT NULL,
  "token" TEXT NOT NULL UNIQUE,
  "createdAt" DATE NOT NULL,
  "updatedAt" DATE NOT NULL,
  "ipAddress" TEXT,
  "userAgent" TEXT,
  "userId" TEXT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "account" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "accountId" TEXT NOT NULL,
  "providerId" TEXT NOT NULL,
  "userId" TEXT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
  "accessToken" TEXT,
  "refreshToken" TEXT,
  "idToken" TEXT,
  "accessTokenExpiresAt" DATE,
  "refreshTokenExpiresAt" DATE,
  "scope" TEXT,
  "password" TEXT,
  "createdAt" DATE NOT NULL,
  "updatedAt" DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS "verification" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "identifier" TEXT NOT NULL,
  "value" TEXT NOT NULL,
  "expiresAt" DATE NOT NULL,
  "createdAt" DATE NOT NULL,
  "updatedAt" DATE NOT NULL
);

CREATE INDEX IF NOT EXISTS "session_userId_idx" ON "session"("userId");
CREATE INDEX IF NOT EXISTS "account_userId_idx" ON "account"("userId");
